### ISSUE TITLE
Unused

### ISSUE THREAD

**Issue by mbrkhrdt** [Disconnect24/legacy-landing#1]
The disconnect24.xyz domain just shows a Mail GO website rather than the actual contents of this repo

**Comment by spotlightishere** [comment]
Ahahah, seems only `https` shows that. ~~Not only does that make no sense, it's proxied by CloudFlare so nginx isn't controlling.~~ (Turns out it is.)

**Comment by spotlightishere** [comment]
Thanks, we've added a server entry for https://disconnect24.xyz. In the meantime, we'll need to figure out what's causing nginx to default to returning Mail-GO for all interfaces.
